---

    aws_region: ap-northeast-2   #서율리전
#    aws_region: ap-northeast-1   #도쿄리전
    vpc_name: simple-vpc2
    vpc_cidr_block: 10.210.0.0/16  #B클래스 크기
    subnet_cidr_block: 10.210.1.0/24  #C클래스 크기
    instance_image: ami-0b827f3319f7447c6  #서울리전
#    instance_image: ami-06098fd00463352b6  #도쿄리전
    ec2_key_name: youngki-seoul
    instance_type: t3.nano