---

  - name: Create subnet
    ec2_vpc_subnet:
      state: present
      region: "{{ aws_region }}"            #region은 반드시 추가하자
      vpc_id: "{{ result_vpc.vpc.id }}"
      cidr: "{{ subnet_cidr_block }}"
      tags:
        Name: webserver Subnet
    register: result_subnet