---

  - name: create vpc2
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        Name: "{{ vpc_name }}"
      tenancy: default      #전용 VPC가 아닌 기본 VPC사용
    register: result_vpc